{% set name = "streamlit_tags" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit_tags-{{ version }}.tar.gz
  sha256: 0e337c1f08d825f793e58d09ea6ccb72d36e2511c863f519d48d051779e728e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - streamlit >=0.63

test:
  imports:
    - streamlit_tags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gagan3012/streamlit-tags
  summary: Tags custom component for Streamlit
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - gagan3012
